name = "wainalbot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "488df7cf0f704e11ae3cdacc7a884058"

[vars]
# Estas variables se configuran como secrets, no acá
# WHATSAPP_TOKEN
# VERIFY_TOKEN
# ANTHROPIC_API_KEY
